ddddd<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.cubrid.cubridmigration</groupId>
        <artifactId>product</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../</relativePath>
    </parent>
    <artifactId>com.cubrid.cubridmigration.desktop</artifactId>
    <packaging>eclipse-repository</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-p2-director-plugin</artifactId>
                <version>${tycho-version}</version>
                <configuration>
                    <formats>
                        <win32>zip</win32>
                        <linux>tar.gz</linux>
                        <macosx>tar.gz</macosx>
                        <solaris>tar.gz</solaris>
                    </formats>
                    <products>
                        <product>
                            <id>com.cubrid.cubridmigration.desktop</id>
                            <archiveFileName>CUBRIDMigration-${cubridmigration-version}</archiveFileName>
                            <rootFolders>
                                <!-- for MacOSX, make sure you use a folder ending with .app , see bug 463670 -->
                                <macosx>Cubridmigration.app</macosx>
                                <win32>cubridmigration</win32>
                                <linux>cubridmigration</linux>
                                <solaris>cubridmigration</solaris>
                            </rootFolders>
                        </product>
                    </products>
                </configuration>
                <executions>
                    <execution>
                        <id>materialize-products</id>
                        <goals>
                            <goal>materialize-products</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            
            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-p2-repository-plugin</artifactId>
                <version>${tycho-version}</version>
                <executions>
                    <execution>
                        <id>default-repository</id>
                            <goals>
                                <goal>assemble-repository</goal>
                            </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <id>download-jre</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <get src="${jre.download.url}/OpenJDK21U-jre_x64_windows_hotspot_21.0.7_6.zip" dest="${project.build.directory}/win-jre.zip" />
                                <get src="${jre.download.url}/OpenJDK21U-jre_x64_linux_hotspot_21.0.7_6.tar.gz" dest="${project.build.directory}/linux-jre.tar.gz" />
                                <get src="${jre.download.url}/OpenJDK21U-jre_x64_mac_hotspot_21.0.7_6.tar.gz" dest="${project.build.directory}/mac-x64-jre.tar.gz" />
                                <get src="${jre.download.url}/OpenJDK21U-jre_aarch64_mac_hotspot_21.0.7_6.tar.gz" dest="${project.build.directory}/mac-aarch64-jre.tar.gz" />
                            </target>
                        </configuration>
                    </execution>
                    <execution>
                        <id>unpack-jre</id>
                        <phase>package</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <property name="jre.dir" value="${project.build.directory}/jre"/>
                                <unzip src="${project.build.directory}/win-jre.zip" dest="${jre.dir}/win">
                                    <mapper type="regexp" from="^[^/]+/(.*)$" to="win-jre/\1"/>
                                </unzip>
                                <untar src="${project.build.directory}/linux-jre.tar.gz" dest="${jre.dir}/linux" compression="gzip">
                                    <mapper type="regexp" from="^[^/]+/(.*)$" to="linux-jre/\1"/>
                                </untar>
                                <chmod perm="755">
                                    <fileset dir="${jre.dir}/linux/linux-jre/bin" includes="**/*"/>
                                </chmod>
                                <untar src="${project.build.directory}/mac-x64-jre.tar.gz" dest="${jre.dir}/mac-x64" compression="gzip">
                                    <mapper type="regexp" from="^[^/]+/(.*)$" to="mac-x64-jre/\1"/>
                                </untar>
                                <chmod perm="755">
                                    <fileset dir="${jre.dir}/mac-x64/mac-x64-jre/Contents/Home/bin" includes="**/*"/>
                                </chmod>
                                <untar src="${project.build.directory}/mac-aarch64-jre.tar.gz" dest="${jre.dir}/mac-aarch64" compression="gzip">
                                    <mapper type="regexp" from="^[^/]+/(.*)$" to="mac-aarch64-jre/\1"/>
                                </untar>
                                <chmod perm="755">
                                    <fileset dir="${jre.dir}/mac-aarch64/mac-aarch64-jre/Contents/Home/bin" includes="**/*"/>
                                </chmod>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <id>migration-windows</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>${basedir}/windows.xml</descriptor>
                            </descriptors>
                            <finalName>${cubridmigration-desktop}-${cubridmigration-version}</finalName>
                        </configuration>
                    </execution>
                    
                    <execution>
                        <id>migration-linux</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>${basedir}/linux.xml</descriptor>
                            </descriptors>
                            <finalName>${cubridmigration-desktop}-${cubridmigration-version}</finalName>
                        </configuration>
                    </execution>
                    
                    <execution>
                        <id>migration-mac</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>${basedir}/mac.xml</descriptor>
                            </descriptors>
                            <finalName>${cubridmigration-desktop}-${cubridmigration-version}</finalName>
                        </configuration>
                    </execution>

                    <execution>
                        <id>migration-mac-aarch64</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>${basedir}/mac-aarch64.xml</descriptor>
                            </descriptors>
                            <finalName>${cubridmigration-desktop}-${cubridmigration-version}</finalName>
                        </configuration>
                    </execution>
                    
                    <execution>
                        <id>site</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>${basedir}/site.xml</descriptor>
                            </descriptors>
                            <finalName>${cubridmigration-desktop}-site-${cubridmigration-version}</finalName>
                            <appendAssemblyId>false</appendAssemblyId>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <tarLongFileMode>posix</tarLongFileMode>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
